CREATE TABLE alertas
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    pet_id           BIGINT               NOT NULL,
    veterinario_id   BIGINT               NOT NULL,

    tipo             VARCHAR(20)          NOT NULL,
    titulo           VARCHAR(150)         NOT NULL,
    descricao        VARCHAR(1000),

    data_inicio      TIMESTAMP            NOT NULL,
    frequencia_horas INTEGER,
    data_fim         TIMESTAMP,

    ativo            BOOLEAN DEFAULT TRUE NOT NULL,

    CONSTRAINT fk_alerta_pet
        FOREIGN KEY (pet_id)
            REFERENCES pets (id),

    CONSTRAINT fk_alerta_veterinario
        FOREIGN KEY (veterinario_id)
            REFERENCES veterinarios (id),

    CONSTRAINT chk_alerta_tipo
        CHECK (
            tipo IN (
                     'CONSULTA',
                     'REMEDIO',
                     'ALIMENTACAO',
                     'EXERCICIO',
                     'OUTROS'
                )
            ),

    CONSTRAINT chk_alerta_frequencia
        CHECK (
            frequencia_horas IS NULL
                OR frequencia_horas > 0
            ),

    CONSTRAINT chk_alerta_datas
        CHECK (
            data_fim IS NULL
                OR data_fim >= data_inicio
            )
);