CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome         VARCHAR(100)        NOT NULL,
    email        VARCHAR(150) UNIQUE NOT NULL,
    senha        VARCHAR(255)        NOT NULL,
    telefone     VARCHAR(20),
    tipo_usuario VARCHAR(20)         NOT NULL,
    ativo        BOOLEAN   DEFAULT TRUE,
    ultimo_login TIMESTAMP,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_tipo_usuario
        CHECK (tipo_usuario IN ('TUTOR', 'VETERINARIO'))
);