CREATE TABLE veterinarios
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT      NOT NULL,
    crmv          VARCHAR(50) NOT NULL,
    especialidade VARCHAR(100),
    descricao     VARCHAR(500),

    CONSTRAINT fk_vet_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);