CREATE TABLE pets
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    nome            VARCHAR(100) NOT NULL,
    especie         VARCHAR(50)  NOT NULL,
    raca            VARCHAR(100),
    data_nascimento DATE,
    observacoes     VARCHAR(500),

    CONSTRAINT fk_pet_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);