CREATE TABLE pet_veterinario
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id         BIGINT NOT NULL,
    veterinario_id BIGINT NOT NULL,
    data_inicio    DATE    DEFAULT CURRENT_DATE,
    ativo          BOOLEAN DEFAULT TRUE,
    observacoes    VARCHAR(500),

    CONSTRAINT fk_pv_pet
        FOREIGN KEY (pet_id) REFERENCES pets (id),

    CONSTRAINT fk_pv_vet
        FOREIGN KEY (veterinario_id) REFERENCES veterinarios (id)
);