CREATE TABLE registros
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entrada_id    BIGINT      NOT NULL,
    tipo          VARCHAR(50) NOT NULL,
    subtipo       VARCHAR(50),
    valor         DECIMAL(10, 2),
    unidade       VARCHAR(20),
    nota          VARCHAR(500),
    horario       TIMESTAMP,
    atualizado_em TIMESTAMP,

    CONSTRAINT fk_registro_entrada
        FOREIGN KEY (entrada_id) REFERENCES diario_entradas (id)
);