CREATE TABLE comentarios
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    entrada_id BIGINT        NOT NULL,
    user_id    BIGINT        NOT NULL,

    comentario VARCHAR(1000) NOT NULL,
    criado_em  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    editado_em TIMESTAMP,

    CONSTRAINT fk_comentario_entrada
        FOREIGN KEY (entrada_id) REFERENCES diario_entradas (id),

    CONSTRAINT fk_comentario_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);