CREATE TABLE insights
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    pet_id       BIGINT        NOT NULL,

    tipo         VARCHAR(100)  NOT NULL,
    descricao    VARCHAR(1000) NOT NULL,
    origem_regra VARCHAR(100),
    nivel_alerta VARCHAR(10),
    data_inicio  DATE,
    data_fim     DATE,
    criado_em    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    gerado_por   VARCHAR(50),
    status       VARCHAR(20),
    contexto     CLOB,

    CONSTRAINT fk_insight_pet
        FOREIGN KEY (pet_id) REFERENCES pets (id),

    CONSTRAINT chk_nivel_alerta
        CHECK (nivel_alerta IN ('BAIXO', 'MEDIO', 'ALTO')),

    CONSTRAINT chk_insight_status
        CHECK (status IN ('ATIVO', 'RESOLVIDO', 'IGNORADO'))
);